image:
  file: dockerfile  
tasks:
  - init: echo 'Welcome to the dev-container for Angular'     
ports:
  - port: 8000
    onOpen: open-preview    
  - port: 8888
    onOpen: open-preview
  - port: 8080
    onOpen: open-preview
